language: node_js
node_js:
    - 6
    - 7
    - node
before_install:
    - sudo apt-get install unixodbc unixodbc-dev
script:
- webpack
- ./node_modules/.bin/mocha --timeout 20000 --require ./test/tests.js
